######################################################################
# Automatically generated by qmake (3.1) Sun Jun 4 13:53:57 2017
######################################################################

TEMPLATE = app
TARGET = cpp
INCLUDEPATH += .

# Input
HEADERS += windows.h
SOURCES += main.cc windows.cc

QT += widgets core gui
